building_name: building
levels:
  B1:
    lanes:
    - - 0
      - 1
      - {}
    - - 1
      - 0
      - {}
    - - 0
      - 2
      - {}
    - - 2
      - 0
      - {}
    - - 2
      - 3
      - {}
    - - 3
      - 2
      - {}
    - - 3
      - 4
      - {door_name: chart_cssd_door}
    - - 4
      - 3
      - {door_name: chart_cssd_door}
    - - 5
      - 6
      - {demo_mock_floor_name: L3, demo_mock_lift_name: LF001}
    - - 6
      - 5
      - {demo_mock_floor_name: L3, demo_mock_lift_name: LF001}
    - - 1
      - 7
      - {}
    - - 7
      - 1
      - {}
    - - 7
      - 5
      - {demo_mock_floor_name: B1, demo_mock_lift_name: LF001, door_name: LF001}
    - - 5
      - 7
      - {demo_mock_floor_name: B1, demo_mock_lift_name: LF001, door_name: LF001}
    - - 8
      - 5
      - {demo_mock_floor_name: L3, demo_mock_lift_name: LF001}
    - - 5
      - 8
      - {demo_mock_floor_name: L3, demo_mock_lift_name: LF001}
    - - 9
      - 7
      - {}
    - - 7
      - 9
      - {}
    - - 9
      - 10
      - {}
    - - 10
      - 9
      - {}
    - - 10
      - 11
      - {}
    - - 11
      - 10
      - {}
    - - 12
      - 10
      - {}
    - - 10
      - 12
      - {}
    vertices:
    - - 18.01255272256649
      - -15.51754712329592
      - {is_charger: true, is_parking_spot: true, name: mir_start, spawn_robot_name: mir100,
        spawn_robot_type: MiR100}
    - - 17.934365577611143
      - -20.16542755479477
      - {is_parking_spot: true, name: before_lift}
    - - 16.310471871851544
      - -15.52620914472338
      - {name: front_door}
    - - 12.41898560808649
      - -15.53694445468634
      - {is_parking_spot: true, name: cssd_enter}
    - - 9.917569349785907
      - -15.572177640228281
      - {dock_name: '', is_parking_spot: false, name: cssd}
    - - 22.387802071427807
      - -21.617200153423124
      - {name: lift_exit}
    - - 22.39487414765933
      - -22.82619448041284
      - {is_parking_spot: true, name: ot}
    - - 17.94342190544719
      - -21.654404871008026
      - {name: lift_enter}
    - - 28.255412139879333
      - -21.422997887410723
      - {is_parking_spot: true, name: AMR2_start}
    - - 17.906102711808185
      - -22.813296844983405
      - {is_parking_spot: true, name: ''}
    - - 14.855315869846237
      - -22.840529426299398
      - {is_parking_spot: true, name: pre_parking}
    - - 13.112010920091063
      - -22.82690677586062
      - {is_parking_spot: true, name: ward_entrance}
    - - 14.841693219407457
      - -23.84837660666086
      - {is_parking_spot: true, name: AMR2_parking}
